// apps/web/src/app/features/auth/login-screen.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule } from 'lucide-angular';
import { ApiService } from '../../core/api/api.service';
import { AuthService } from '../../core/auth/auth.service';

@Component({
  selector: 'app-login-screen',
  standalone: true,
  imports: [FormsModule, LucideAngularModule],
  templateUrl: './login-screen.component.html',
  styleUrl: './login-screen.component.css'
})
export class LoginScreenComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthService);

  readonly adminName = signal('');
  readonly email = signal('admin@pdi.local');
  readonly password = signal('admin123');
  readonly canCreateAdmin = signal(false);
  readonly error = signal<string | null>(null);
  readonly isSubmitting = signal(false);

  ngOnInit() {
    void this.api
      .bootstrapStatus()
      .then((status) => {
        this.canCreateAdmin.set(status.canCreateAdmin);

        if (status.canCreateAdmin) {
          this.email.set('');
          this.password.set('');
        }
      })
      .catch(() => this.canCreateAdmin.set(false));
  }

  readonly handleSubmit = async () => {
    this.error.set(null);
    this.isSubmitting.set(true);

    try {
      if (this.canCreateAdmin()) {
        await this.auth.createBootstrapAdmin({
          email: this.email(),
          name: this.adminName(),
          password: this.password()
        });
        return;
      }

      await this.auth.login(this.email(), this.password());
    } catch {
      this.error.set(this.canCreateAdmin() ? 'Could not create admin user' : 'Invalid email or password');
    } finally {
      this.isSubmitting.set(false);
    }
  };
}

<main class="login-shell">
  <section class="login-visual" aria-label="PDI Portal">
    <div>
      <p>PDI Portal</p>
      <h1>Development plans with a living canvas.</h1>
      <span>Goals, actions, feedback loops and team follow-up in one workspace.</span>
    </div>
  </section>

  <form class="login-panel" [attr.aria-busy]="isSubmitting()" (ngSubmit)="handleSubmit()">
    <i-lucide name="lock-keyhole" aria-hidden="true" />
    <h2>{{ canCreateAdmin() ? 'Create first Tech Lead' : 'Sign in' }}</h2>

    @if (canCreateAdmin()) {
      <label>
        Name
        <input
          #nameControl="ngModel"
          [ngModel]="adminName()"
          (ngModelChange)="adminName.set($event)"
          [disabled]="isSubmitting()"
          [attr.aria-invalid]="nameControl.invalid && nameControl.touched ? 'true' : null"
          [attr.aria-describedby]="nameControl.invalid && nameControl.touched ? 'login-name-error' : null"
          minlength="2"
          name="adminName"
          required
          type="text"
        />
        @if (nameControl.invalid && nameControl.touched) {
          <small class="field-error" id="login-name-error">
            @if (nameControl.errors?.['required']) {
              Name is required
            } @else if (nameControl.errors?.['minlength']) {
              Name must be at least 2 characters
            }
          </small>
        }
      </label>
    }

    <label>
      Email
      <input
        #emailControl="ngModel"
        [ngModel]="email()"
        (ngModelChange)="email.set($event)"
        [disabled]="isSubmitting()"
        [attr.aria-invalid]="emailControl.invalid && emailControl.touched ? 'true' : null"
        [attr.aria-describedby]="emailControl.invalid && emailControl.touched ? 'login-email-error' : null"
        name="email"
        required
        type="email"
      />
      @if (emailControl.invalid && emailControl.touched) {
        <small class="field-error" id="login-email-error">
          @if (emailControl.errors?.['required']) {
            Email is required
          } @else if (emailControl.errors?.['email']) {
            Enter a valid email address
          }
        </small>
      }
    </label>

    <label>
      Password
      <input
        #passwordControl="ngModel"
        [minlength]="canCreateAdmin() ? 8 : 6"
        [ngModel]="password()"
        (ngModelChange)="password.set($event)"
        [disabled]="isSubmitting()"
        [attr.aria-invalid]="passwordControl.invalid && passwordControl.touched ? 'true' : null"
        [attr.aria-describedby]="passwordControl.invalid && passwordControl.touched ? 'login-password-error' : null"
        name="password"
        required
        type="password"
      />
      @if (passwordControl.invalid && passwordControl.touched) {
        <small class="field-error" id="login-password-error">
          @if (passwordControl.errors?.['required']) {
            Password is required
          } @else if (passwordControl.errors?.['minlength']) {
            Password must be at least {{ canCreateAdmin() ? 8 : 6 }} characters
          }
        </small>
      }
    </label>

    @if (error()) {
      <p class="form-error">{{ error() }}</p>
    }

    <button [disabled]="isSubmitting()" type="submit">
      @if (isSubmitting()) {
        <span class="login-spinner" aria-hidden="true"></span>
      } @else {
        <i-lucide [name]="canCreateAdmin() ? 'user-plus' : 'log-in'" [size]="18" />
      }
      {{
        isSubmitting()
            ? canCreateAdmin()
            ? 'Creating Tech Lead'
            : 'Signing in'
          : canCreateAdmin()
            ? 'Create Tech Lead'
            : 'Enter platform'
      }}
    </button>
  </form>
</main>

// apps/web/src/ui/LoginScreen.tsx
import { FormEvent, useEffect, useState } from 'react';
import { LockKeyhole, LogIn, UserPlus } from 'lucide-react';
import { api } from '../api/client';
import { useAuth } from '../store/auth';

export const LoginScreen = () => {
  const createBootstrapAdmin = useAuth((state) => state.createBootstrapAdmin);
  const login = useAuth((state) => state.login);
  const [adminName, setAdminName] = useState('');
  const [email, setEmail] = useState('admin@pdi.local');
  const [password, setPassword] = useState('admin123');
  const [canCreateAdmin, setCanCreateAdmin] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    void api
      .bootstrapStatus()
      .then((status) => {
        setCanCreateAdmin(status.canCreateAdmin);
        if (status.canCreateAdmin) {
          setEmail('');
          setPassword('');
        }
      })
      .catch(() => setCanCreateAdmin(false));
  }, []);

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setError(null);
    setIsSubmitting(true);

    try {
      if (canCreateAdmin) {
        await createBootstrapAdmin({ email, name: adminName, password });
        return;
      }

      await login(email, password);
    } catch {
      setError(canCreateAdmin ? 'Could not create admin user' : 'Invalid email or password');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <main className="login-shell">
      <section className="login-visual" aria-label="PDI Portal">
        <div>
          <p>PDI Portal</p>
          <h1>Development plans with a living canvas.</h1>
          <span>Goals, actions, feedback loops and team follow-up in one workspace.</span>
        </div>
      </section>

      <form className="login-panel" onSubmit={handleSubmit}>
        <LockKeyhole aria-hidden="true" />
        <h2>{canCreateAdmin ? 'Create first admin' : 'Sign in'}</h2>
        {canCreateAdmin ? (
          <label>
            Name
            <input
              minLength={2}
              onChange={(event) => setAdminName(event.target.value)}
              required
              type="text"
              value={adminName}
            />
          </label>
        ) : null}
        <label>
          Email
          <input value={email} onChange={(event) => setEmail(event.target.value)} required type="email" />
        </label>
        <label>
          Password
          <input
            minLength={canCreateAdmin ? 8 : 6}
            onChange={(event) => setPassword(event.target.value)}
            required
            type="password"
            value={password}
          />
        </label>
        {error ? <p className="form-error">{error}</p> : null}
        <button disabled={isSubmitting} type="submit">
          {canCreateAdmin ? <UserPlus size={18} /> : <LogIn size={18} />}
          {isSubmitting ? (canCreateAdmin ? 'Creating admin' : 'Signing in') : canCreateAdmin ? 'Create admin' : 'Enter platform'}
        </button>
      </form>
    </main>
  );
};
